version: '3'
services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "marketplacedb"
      POSTGRES_USER: "bibamet"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root
      - ./dbroot/pssqldump.sql:/docker-entrypoint-initdb.d/db.sql